name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependency
        run: |
            sudo apt-get update
            sudo apt-get install -y libudev-dev

      - name: Build
        run: cargo build --release

      - uses: actions/upload-artifact@v4
        with:
          name: 'container-hotplug'
          path: target/release/container-hotplug

      - uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: target/release/container-hotplug
